/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdesaoRouteImport } from './routes/adesao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmadoRouteImport } from './routes/confirmado'
import { Route as MinhaAdesaoRouteImport } from './routes/minha-adesao'
import { Route as SenseiRouteImport } from './routes/sensei'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAtletaRouteImport } from './routes/_authenticated/atleta'
import { Route as AuthenticatedAdminDojosRouteImport } from './routes/_authenticated/admin_.dojos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdesaoRoute = AdesaoRouteImport.update({
  id: '/adesao',
  path: '/adesao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmadoRoute = ConfirmadoRouteImport.update({
  id: '/confirmado',
  path: '/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAdesaoRoute = MinhaAdesaoRouteImport.update({
  id: '/minha-adesao',
  path: '/minha-adesao',
  getParentRoute: () => rootRouteImport,
} as any)
const SenseiRoute = SenseiRouteImport.update({
  id: '/sensei',
  path: '/sensei',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtletaRoute = AuthenticatedAtletaRouteImport.update({
  id: '/atleta',
  path: '/atleta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDojosRoute = AuthenticatedAdminDojosRouteImport.update({
  id: '/admin_/dojos',
  path: '/admin/dojos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adesao': typeof AdesaoRoute
  '/auth': typeof AuthRoute
  '/confirmado': typeof ConfirmadoRoute
  '/minha-adesao': typeof MinhaAdesaoRoute
  '/sensei': typeof SenseiRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atleta': typeof AuthenticatedAtletaRoute
  '/admin/dojos': typeof AuthenticatedAdminDojosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adesao': typeof AdesaoRoute
  '/auth': typeof AuthRoute
  '/confirmado': typeof ConfirmadoRoute
  '/minha-adesao': typeof MinhaAdesaoRoute
  '/sensei': typeof SenseiRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atleta': typeof AuthenticatedAtletaRoute
  '/admin/dojos': typeof AuthenticatedAdminDojosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adesao': typeof AdesaoRoute
  '/auth': typeof AuthRoute
  '/confirmado': typeof ConfirmadoRoute
  '/minha-adesao': typeof MinhaAdesaoRoute
  '/sensei': typeof SenseiRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/atleta': typeof AuthenticatedAtletaRoute
  '/_authenticated/admin_/dojos': typeof AuthenticatedAdminDojosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adesao'
    | '/auth'
    | '/confirmado'
    | '/minha-adesao'
    | '/sensei'
    | '/admin'
    | '/atleta'
    | '/admin/dojos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adesao'
    | '/auth'
    | '/confirmado'
    | '/minha-adesao'
    | '/sensei'
    | '/admin'
    | '/atleta'
    | '/admin/dojos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/adesao'
    | '/auth'
    | '/confirmado'
    | '/minha-adesao'
    | '/sensei'
    | '/_authenticated/admin'
    | '/_authenticated/atleta'
    | '/_authenticated/admin_/dojos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdesaoRoute: typeof AdesaoRoute
  AuthRoute: typeof AuthRoute
  ConfirmadoRoute: typeof ConfirmadoRoute
  MinhaAdesaoRoute: typeof MinhaAdesaoRoute
  SenseiRoute: typeof SenseiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adesao': {
      id: '/adesao'
      path: '/adesao'
      fullPath: '/adesao'
      preLoaderRoute: typeof AdesaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmado': {
      id: '/confirmado'
      path: '/confirmado'
      fullPath: '/confirmado'
      preLoaderRoute: typeof ConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-adesao': {
      id: '/minha-adesao'
      path: '/minha-adesao'
      fullPath: '/minha-adesao'
      preLoaderRoute: typeof MinhaAdesaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensei': {
      id: '/sensei'
      path: '/sensei'
      fullPath: '/sensei'
      preLoaderRoute: typeof SenseiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atleta': {
      id: '/_authenticated/atleta'
      path: '/atleta'
      fullPath: '/atleta'
      preLoaderRoute: typeof AuthenticatedAtletaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/dojos': {
      id: '/_authenticated/admin_/dojos'
      path: '/admin/dojos'
      fullPath: '/admin/dojos'
      preLoaderRoute: typeof AuthenticatedAdminDojosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAtletaRoute: typeof AuthenticatedAtletaRoute
  AuthenticatedAdminDojosRoute: typeof AuthenticatedAdminDojosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAtletaRoute: AuthenticatedAtletaRoute,
  AuthenticatedAdminDojosRoute: AuthenticatedAdminDojosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdesaoRoute: AdesaoRoute,
  AuthRoute: AuthRoute,
  ConfirmadoRoute: ConfirmadoRoute,
  MinhaAdesaoRoute: MinhaAdesaoRoute,
  SenseiRoute: SenseiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
