/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdesaoRouteImport } from './routes/adesao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmadoRouteImport } from './routes/confirmado'
import { Route as MinhaAdesaoRouteImport } from './routes/minha-adesao'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SenseiRouteImport } from './routes/sensei'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAtletaRouteImport } from './routes/_authenticated/atleta'
import { Route as AuthenticatedClubeRouteImport } from './routes/_authenticated/clube'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedAdminDojosRouteImport } from './routes/_authenticated/admin_.dojos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdesaoRoute = AdesaoRouteImport.update({
  id: '/adesao',
  path: '/adesao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmadoRoute = ConfirmadoRouteImport.update({
  id: '/confirmado',
  path: '/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAdesaoRoute = MinhaAdesaoRouteImport.update({
  id: '/minha-adesao',
  path: '/minha-adesao',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SenseiRoute = SenseiRouteImport.update({
  id: '/sensei',
  path: '/sensei',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtletaRoute = AuthenticatedAtletaRouteImport.update({
  id: '/atleta',
  path: '/atleta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClubeRoute = AuthenticatedClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDojosRoute = AuthenticatedAdminDojosRouteImport.update({
  id: '/admin_/dojos',
  path: '/admin/dojos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adesao': typeof AdesaoRoute
  '/auth': typeof AuthRoute
  '/confirmado': typeof ConfirmadoRoute
  '/minha-adesao': typeof MinhaAdesaoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sensei': typeof SenseiRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atleta': typeof AuthenticatedAtletaRoute
  '/clube': typeof AuthenticatedClubeRoute
  '/c/$slug': typeof CSlugRoute
  '/admin/dojos': typeof AuthenticatedAdminDojosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adesao': typeof AdesaoRoute
  '/auth': typeof AuthRoute
  '/confirmado': typeof ConfirmadoRoute
  '/minha-adesao': typeof MinhaAdesaoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sensei': typeof SenseiRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atleta': typeof AuthenticatedAtletaRoute
  '/clube': typeof AuthenticatedClubeRoute
  '/c/$slug': typeof CSlugRoute
  '/admin/dojos': typeof AuthenticatedAdminDojosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adesao': typeof AdesaoRoute
  '/auth': typeof AuthRoute
  '/confirmado': typeof ConfirmadoRoute
  '/minha-adesao': typeof MinhaAdesaoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/ranking': typeof RankingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sensei': typeof SenseiRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/atleta': typeof AuthenticatedAtletaRoute
  '/_authenticated/clube': typeof AuthenticatedClubeRoute
  '/c/$slug': typeof CSlugRoute
  '/_authenticated/admin_/dojos': typeof AuthenticatedAdminDojosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adesao'
    | '/auth'
    | '/confirmado'
    | '/minha-adesao'
    | '/privacidade'
    | '/ranking'
    | '/reset-password'
    | '/sensei'
    | '/termos'
    | '/admin'
    | '/atleta'
    | '/clube'
    | '/c/$slug'
    | '/admin/dojos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adesao'
    | '/auth'
    | '/confirmado'
    | '/minha-adesao'
    | '/privacidade'
    | '/ranking'
    | '/reset-password'
    | '/sensei'
    | '/termos'
    | '/admin'
    | '/atleta'
    | '/clube'
    | '/c/$slug'
    | '/admin/dojos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/adesao'
    | '/auth'
    | '/confirmado'
    | '/minha-adesao'
    | '/privacidade'
    | '/ranking'
    | '/reset-password'
    | '/sensei'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/atleta'
    | '/_authenticated/clube'
    | '/c/$slug'
    | '/_authenticated/admin_/dojos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdesaoRoute: typeof AdesaoRoute
  AuthRoute: typeof AuthRoute
  ConfirmadoRoute: typeof ConfirmadoRoute
  MinhaAdesaoRoute: typeof MinhaAdesaoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RankingRoute: typeof RankingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SenseiRoute: typeof SenseiRoute
  TermosRoute: typeof TermosRoute
  CSlugRoute: typeof CSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adesao': {
      id: '/adesao'
      path: '/adesao'
      fullPath: '/adesao'
      preLoaderRoute: typeof AdesaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmado': {
      id: '/confirmado'
      path: '/confirmado'
      fullPath: '/confirmado'
      preLoaderRoute: typeof ConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-adesao': {
      id: '/minha-adesao'
      path: '/minha-adesao'
      fullPath: '/minha-adesao'
      preLoaderRoute: typeof MinhaAdesaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensei': {
      id: '/sensei'
      path: '/sensei'
      fullPath: '/sensei'
      preLoaderRoute: typeof SenseiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atleta': {
      id: '/_authenticated/atleta'
      path: '/atleta'
      fullPath: '/atleta'
      preLoaderRoute: typeof AuthenticatedAtletaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clube': {
      id: '/_authenticated/clube'
      path: '/clube'
      fullPath: '/clube'
      preLoaderRoute: typeof AuthenticatedClubeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/dojos': {
      id: '/_authenticated/admin_/dojos'
      path: '/admin/dojos'
      fullPath: '/admin/dojos'
      preLoaderRoute: typeof AuthenticatedAdminDojosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAtletaRoute: typeof AuthenticatedAtletaRoute
  AuthenticatedClubeRoute: typeof AuthenticatedClubeRoute
  AuthenticatedAdminDojosRoute: typeof AuthenticatedAdminDojosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAtletaRoute: AuthenticatedAtletaRoute,
  AuthenticatedClubeRoute: AuthenticatedClubeRoute,
  AuthenticatedAdminDojosRoute: AuthenticatedAdminDojosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdesaoRoute: AdesaoRoute,
  AuthRoute: AuthRoute,
  ConfirmadoRoute: ConfirmadoRoute,
  MinhaAdesaoRoute: MinhaAdesaoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RankingRoute: RankingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SenseiRoute: SenseiRoute,
  TermosRoute: TermosRoute,
  CSlugRoute: CSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
