/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhooksGreennRouteImport } from './routes/api/public/webhooks/greenn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksGreennRoute = ApiPublicWebhooksGreennRouteImport.update({
  id: '/api/public/webhooks/greenn',
  path: '/api/public/webhooks/greenn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/webhooks/greenn': typeof ApiPublicWebhooksGreennRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/webhooks/greenn': typeof ApiPublicWebhooksGreennRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/webhooks/greenn': typeof ApiPublicWebhooksGreennRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/webhooks/greenn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/webhooks/greenn'
  id: '__root__' | '/' | '/api/public/webhooks/greenn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicWebhooksGreennRoute: typeof ApiPublicWebhooksGreennRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/greenn': {
      id: '/api/public/webhooks/greenn'
      path: '/api/public/webhooks/greenn'
      fullPath: '/api/public/webhooks/greenn'
      preLoaderRoute: typeof ApiPublicWebhooksGreennRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicWebhooksGreennRoute: ApiPublicWebhooksGreennRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
